### ISSUE TITLE
Cannot get property PropertyDirection

### ISSUE THREAD

**Issue by Sasikaa** [FireBall1725/Graves#8] opened 2016-01-22 08:36 UTC
I'm finding RoguelikeDungeons and try killing the tainted mob. When killing me, teleport back to the Death waypoint. Try crack my graves, crash.

This is my crashlog:
http://pastebin.com/rAGqkcZR

**Comment by FusionLord** [comment] 2016-01-22 11:49
Duplicate of #6

**Closed as completed by FusionLord** 2016-01-22 11:49 UTC
Labels: bug, duplicate

**Comment by Sasikaa** [comment] 2016-01-22 20:00
Yes, duplicate, but i use b22 version. Try b23, and perhaps fixing it.

**Comment by FusionLord** [comment] 2016-01-22 21:04
Yes, build 23 has fixed this issue.
