### ISSUE TITLE
No grave when killed near water

### ISSUE THREAD

**Issue by danneker** [FireBall1725/Graves#35] opened 2016-03-19 21:31 UTC
I was playing Tarazan with my grappling hook in a jungle when I fell. I must have hit the ground because if I landed in the river I would not have died. However the marker for my death in Journey Map has my death placed in the middle of the nearby river. I have looked all over for the my grave, around the river, in the river, in the caves under the river, etc. I can not find any grave. What happens when we die in water? Is a grave not created?

**Comment by FusionLord** [comment] 2016-03-26 18:48
I cannot reproduce this, grave should spawn in the water.

**Comment by FusionLord** [comment] 2016-03-30 01:25
Does it spawn using the new b47 version?

**Comment by danneker** [comment] 2016-03-30 21:11
I still do not see any grave with the new b47 version. I looked every where around the death marked in journey map. I have not had any other problems with this mod however, so maybe the problem is not with the mod but another?

**Comment by FusionLord** [comment] 2016-03-30 22:00
well journey map places a marker where you die, I would suggest you add [TomTom](http://minecraft.curseforge.com/projects/tomtom) as it will point you to your grave stone :) I will look further into the gravestone not spawning, but as of yet I still cannot figure out why it wouldn't be spawning where you die.

**Comment by FusionLord** [comment] 2016-06-23 21:24
Fixed in all the newest builds.

**Closed as completed by FusionLord** 2016-06-23 21:24 UTC
